### ISSUE TITLE
Issue: Bootstrap and Other CSS Files Not Loading, Causing Style Breakage

### ISSUE THREAD

**Issue by 0xTanzim** [code-BitLabs/Aquila#5]
Issue Description:
Bootstrap and other CSS files are not loading properly, which is leading to a break in the styling of our application.

![Screenshot 2023-09-23 223644](https://github.com/Tanzimhossain222/Aquila/assets/60542516/c153249c-52ba-4a9d-af8c-d0828828e1db)

**Comment by Tanzimhossain222** [comment]
solved

**Comment by TanzimHossain2** [comment]
okay
